account/urls.py
from django.urls import path

app_name = 'account'

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation, contact_list, update_contact, manager_page

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservations_list'),
    path('reservations/update/<int:pk>', update_reservation, name='update_reserve'),
    path('contact/', contact_list, name='contact_list'),
    path('contact/update/<int:pk>', update_contact, name='update_contact'),
    path('', manager_page, name='manager_page')
]

site_reva_a/urls.py
from django.contrib import admin
from django.urls import path, include
from main_page.views import main_page
from django.conf import settings
from django.conf.urls.static import static
from account.views import registration_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('registration/', registration_view, name='registration_view'),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('accounts/login/', login_view),
    path('', main_page)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from main_page.models import UserReservation, ContactUs
from django.contrib.auth.decorators import login_required, user_passes_test
from main_page.models import InformationInContactUs, Footer
# Create your views here.


def is_manager(user):
    return user.groups.filter(name='manager').exists()

@login_required(login_url='login/')
@user_passes_test(is_manager)
def manager_page(request):
    user_auth = request.user.is_authenticated
    information_in_contact_us = InformationInContactUs.objects.get()
    footer = Footer.objects.get()
    return render(request, 'manager_main_page.html', context={
        'information_in_contact_us': information_in_contact_us,
        'footer': footer,
        'user_auth': user_auth,
    })


@login_required(login_url='login/')
@user_passes_test(is_manager)
def reservation_list(request):
    user_auth = request.user.is_authenticated
    lst = UserReservation.objects.filter(is_processed=False)
    information_in_contact_us = InformationInContactUs.objects.get()
    footer = Footer.objects.get()
    return render(request, 'reservations_list.html', context={
        'lst': lst,
        'information_in_contact_us': information_in_contact_us,
        'footer': footer,
        'user_auth': user_auth,
    })


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_reservation(request, pk):
    UserReservation.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservations_list')


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def contact_list(request):
    user_auth = request.user.is_authenticated
    all_contacts = ContactUs.objects.filter(is_processed=False)
    information_in_contact_us = InformationInContactUs.objects.get()
    footer = Footer.objects.get()
    return render(request, 'contact_list.html', context={
        'all_contacts': all_contacts,
        'information_in_contact_us': information_in_contact_us,
        'footer': footer,
        'user_auth': user_auth,
    })


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_contact(request, pk):
    ContactUs.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:contact_list')

manager/templates/contact_list.html
{% extends 'account.html' %}

{% block content %}

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Contact applications</h2>
          <ol>
            <li><a href="/">Home</a></li>
              <li><a href={% url 'manager:manager_page' %}>Manager</a></li>
            <li>Contact applications</li>
          </ol>
        </div>

      </div>
    </section>

    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in all_contacts %}
                    <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'manager:update_contact' pk=item.pk %}">
                            <button type="button", class="btn btn-primary">Delete application</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.name }}</div>
                    <div class="col-md-3">{{ item.email }}</div>
                    <div class="col-md-3">{{ item.subject }}</div>
                    <div class="col-md-3">{{ item.date_reservation }}</div>
                </div>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-9"><p>{{ item.message }}</p></div>
                </div>
            {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

manager/templates/manager_main_page.html
{% extends 'account.html' %}

{% block content %}

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Managers interface</h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li>Manager</li>
          </ol>
        </div>

      </div>
    </section>

    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                <div class="section-title">
                  <h2><a href={% url 'manager:reservations_list' %}>Reservations</a></h2>
                  <h2><a href={% url 'manager:contact_list' %}>Contact applications</a></h2>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

manager/templates/reservations_list.html
{% extends 'account.html' %}

{% block content %}

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Reservations from guests</h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li><a href={% url 'manager:manager_page' %}>Manager</a></li>
            <li>Reservations from guests</li>
          </ol>
        </div>

      </div>
    </section>

    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in lst %}
                    <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'manager:update_reserve' pk=item.pk %}">
                            <button type="button", class="btn btn-primary">Close application</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.name }}</div>
                    <div class="col-md-3">{{ item.phone }}</div>
                    <div class="col-md-3">{{ item.date_reservation }}</div>
                </div>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-9"><p>{{ item.message }}</p></div>
                </div>
            {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}