account/urls.py
from django.urls import path

app_name = 'account'

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation, contact_list, update_contact, manager_page

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservations_list'),
    path('reservations/update/<int:pk>', update_reservation, name='update_reserve'),
    path('contact/', contact_list, name='contact_list'),
    path('contact/update/<int:pk>', update_contact, name='update_contact'),
    path('', manager_page, name='manager_page')
]

site_reva_a/urls.py
from django.contrib import admin
from django.urls import path, include
from main_page.views import main_page
from django.conf import settings
from django.conf.urls.static import static
from account.views import registration_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('registration/', registration_view, name='registration_view'),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('accounts/login/', login_view),
    path('', main_page)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate

User = get_user_model()


class UserRegistration(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', )

    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_password2(self):
        data = self.cleaned_data

        if data.get('password') == data.get('password2'):
            return data['password2']
        raise forms.ValidationError('Error in passwords')


class UserLogin(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user or not user.check_password(password):
                raise forms.ValidationError('Error in Login or Password')
        else:
            raise forms.ValidationError('Error in Login or Password')
        return super().clean()

account/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistration, UserLogin
from main_page.models import InformationInContactUs, Footer
from django.contrib.auth import login, authenticate, logout


def registration_view(request):
    form = UserRegistration(request.POST or None)
    information_in_contact_us = InformationInContactUs.objects.get()
    footer = Footer.objects.get()
    user_manager = request.user.groups.filter(name='manager').exists()
    user_auth = request.user.is_authenticated
    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        data = {
            'user': new_user,
            'information_in_contact_us': information_in_contact_us,
            'footer': footer}
        return render(request, 'registration_done.html', context=data)

    data = {
        'form': form,
        'information_in_contact_us': information_in_contact_us,
        'footer': footer,
        'user_manager': user_manager,
        'user_auth': user_auth
    }
    return render(request, 'registration.html', context=data)


def login_view(request):
    form = UserLogin(request.POST or None)
    next_get = request.GET.get('next')
    information_in_contact_us = InformationInContactUs.objects.get()
    footer = Footer.objects.get()
    user_manager = request.user.groups.filter(name='manager').exists()
    user_auth = request.user.is_authenticated
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)

        next_post = request.POST.get('next')
        return redirect(next_get or next_post or '/')

    data = {
        'form': form,
        'information_in_contact_us': information_in_contact_us,
        'footer': footer,
        'user_manager': user_manager,
        'user_auth': user_auth
    }

    return render(request, 'login.html', context=data)


def logout_view(request):
    logout(request)
    return redirect('/')

templates/account.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Registration</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %}crel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %}rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/animate.css/animate.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Delicious - v4.8.0
  * Template URL: https://bootstrapmade.com/delicious-free-restaurant-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center fixed-top ">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-center justify-content-lg-start">
<i class="bi bi-phone d-flex align-items-center"><span>{{ information_in_contact_us.phone_for_top_bar }}</span></i>
      <i class="bi bi-clock ms-4 d-none d-lg-flex align-items-center"><span>{{ information_in_contact_us.open_hours_for_top_bar }}</span></i>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <div class="logo me-auto">
        <h1><a href="/">Delicious</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto " href="/#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="/#about">About</a></li>
          <li><a class="nav-link scrollto" href="/#menu">Menu</a></li>
          <li><a class="nav-link scrollto" href="/#specials">Specials</a></li>
          <li><a class="nav-link scrollto" href="/#events">Events</a></li>
          <li><a class="nav-link scrollto" href="/#chefs">Chefs</a></li>
          <li><a class="nav-link scrollto" href="/#gallery">Gallery</a></li>
          <li class="dropdown"><a href="#"><span>Account</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                {% if not user_auth %}
                    <li><a href={% url 'login_view' %}>Log in</a></li>
                {% else %}
                    <li><a href={% url 'logout_view' %}>Log out</a></li>
                {% endif %}
                {% if user_manager %}
                  <li class="dropdown"><a href={% url 'manager:manager_page' %}><span>Manager</span> <i class="bi bi-chevron-right"></i></a>
                    <ul>
                      <li><a href={% url 'manager:reservations_list' %}>Reservations</a></li>
                      <li><a href={% url 'manager:contact_list' %}>Contact applications</a></li>
                    </ul>
                  </li>
                {% endif %}
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="/#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="/#book-a-table" class="book-a-table-btn scrollto">Book a table</a>

    </div>
  </header><!-- End Header -->

  {% block content %}
  {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>{{ footer.header | safe }}</h3>
      <p>{{ footer.heading_text | safe }}</p>
      <div class="social-links">
        <a href="{{ footer.twitter }}" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="{{ footer.facebook }}" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="{{ footer.instagram }}" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="{{ footer.skype }}" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="{{ footer.linked_in }}" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
       {{ footer.site_owner | safe }}
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %} ></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %} ></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %} ></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %} ></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}  ></script>

</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Delicious</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %}  rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/animate.css/animate.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css" %} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Delicious - v4.8.0
  * Template URL: https://bootstrapmade.com/delicious-free-restaurant-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center fixed-top topbar-transparent">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-center justify-content-lg-start">
      <i class="bi bi-phone d-flex align-items-center"><span>{{ information_in_contact_us.phone_for_top_bar }}</span></i>
      <i class="bi bi-clock ms-4 d-none d-lg-flex align-items-center"><span>{{ information_in_contact_us.open_hours_for_top_bar }}</span></i>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <div class="logo me-auto">
        <h1><a href="/">Delicious</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="/#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="/#about">About</a></li>
          <li><a class="nav-link scrollto" href="/#menu">Menu</a></li>
          <li><a class="nav-link scrollto" href="/#specials">Specials</a></li>
          <li><a class="nav-link scrollto" href="/#events">Events</a></li>
          <li><a class="nav-link scrollto" href="/#chefs">Chefs</a></li>
          <li><a class="nav-link scrollto" href="/#gallery">Gallery</a></li>
          <li class="dropdown"><a href="#"><span>Account</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                {% if not user_auth %}
                    <li><a href={% url 'login_view' %}>Log in</a></li>
                {% else %}
                    <li><a href={% url 'logout_view' %}>Log out</a></li>
                {% endif %}
                {% if user_manager %}
                  <li class="dropdown"><a href={% url 'manager:manager_page' %}><span>Manager</span> <i class="bi bi-chevron-right"></i></a>
                    <ul>
                      <li><a href={% url 'manager:reservations_list' %}>Reservations</a></li>
                      <li><a href={% url 'manager:contact_list' %}>Contact applications</a></li>
                    </ul>
                  </li>
                {% endif %}
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="/#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="/#book-a-table" class="book-a-table-btn scrollto">Book a table</a>

    </div>
  </header><!-- End Header -->

  <main id="main">

      {% block content %}
      {% endblock %}


  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>{{ footer.header | safe }}</h3>
      <p>{{ footer.heading_text | safe }}</p>
      <div class="social-links">
        <a href="{{ footer.twitter }}" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="{{ footer.facebook }}" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="{{ footer.instagram }}" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="{{ footer.skype }}" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="{{ footer.linked_in }}" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
       {{ footer.site_owner | safe }}
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

</body>

</html>